name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      uses: maven:3.6.3-jdk-11
      with:
        maven-version: 3.6.3
      run: mvn install
